# genomes 

########################################################################################################
# Run settings
########################################################################################################
CORES: 16 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 120000000000  # limit in bytes
MEMLIMIT_GB: 64G       # mem limit for kallisto

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: tmp
OUTDIR: out

########################################################################################################
# Executables - file paths
########################################################################################################
GGET_EXEC: gget

# Dict of paths to all of the executables for the aligners
EXEC:
  BT: bowtie
  BT2: bowtie2
  BWA: bwa
  BWA_MEM2: bwa-mem2
  KALLISTO: kallisto
  KB: kb
  MINIMAP2: minimap2
  SAMTOOLS: samtools
  STAR: /nfs/home/dmckellar/mambaforge/envs/ref_snake/bin/STAR 

# Dict of species to be included. See `resources/gget_species.txt` for options
SPECIES:
  mus_musculus
  homo_sapiens

#TODO
CUSTOM: "path/to/sample_sheet.csv"
# - space-delimited columns for .fa inputs & .gtf inputs
# - Add separate outputs in `rule all` for custom/gget refs
# - 