# genomes 

########################################################################################################
# Run settings
########################################################################################################

CORES: 24 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 200000000000  # limit in bytes
MEMLIMIT_GB: 300G       # mem limit for kallisto

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: tmp
OUTDIR: out

########################################################################################################
# Executables - file paths
########################################################################################################
# BWA_EXEC: bwa
# BT_EXEC: bowtie
# BT2_EXEC: bowtie2
# STAR_EXEC: STAR 
# KALLISTO_EXEC: kallisto
GGET_EXEC: gget
EXEC:
  BWA: bwa
  BT: bowtie
  BT2: bowtie2
  STAR: STAR 
  KALLISTO: kallisto

SPECIES:
  mus_musculus
  homo_sapiens
