# slurm_config.yml - cluster configuration
__default__:
    job-name: ref_snake
    partition: pe2
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 16 #Request n cores be allocated per node.
    mem: 220G
    output: .slurm_log/%j.log
    chdir: /gpfs/commons/groups/innovation/dwm/ref_snake


