# slurm_config.yml - cluster configuration
__default__:
    job-name: ref_snake
    partition: pe2
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 1 #Request n cores be allocated per node.
    mem: 4G
    output: .slurm/%j.log

# rules...
star_genome:
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 16 #Request n cores be allocated per node.
    mem: 220G
    
star_rRNA:
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 16 #Request n cores be allocated per node.
    mem: 220G

minimap2:
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 16 #Request n cores be allocated per node.
    mem: 128G
    
bwa_mem2:
    time: 2:00:00 # time limit for each job
    nodes: 1
    threads: 16 #Request n cores be allocated per node.
    mem: 128G
    
kb:
    time: 2:00:00 
    nodes: 1
    threads: 16 
    mem: 220G

kb_velocity:
    time: 2:00:00 
    nodes: 1
    threads: 16 
    mem: 220G
    
kb_nucleus:
    time: 2:00:00 
    nodes: 1
    threads: 16 
    mem: 220G